# --------------------------
# Stage 1: Build dependencies
# --------------------------

FROM node:22-alpine AS build

WORKDIR /server

COPY package.json package.json

# Install only production dependencies
RUN npm install 
# RUN npm install  

COPY . .

RUN npm run build

# --------------------------
# Stage 2: Production runtime
# --------------------------

FROM node:22-alpine AS runner

WORKDIR /app

COPY --from=build /server/node_modules node_modules/
COPY --from=build /server/package.json package.json
COPY --from=build /server/drizzle.config.ts drizzle.config.ts
COPY --from=build /server/dist dist/
COPY --from=build /server/.env .env
COPY --from=build /server/src/db/migrations ./dist/db/migrations/ 

EXPOSE 8000

CMD ["sh", "-c", "np npm run start"]
