FROM ubuntu:focal

RUN /usr/bin/apt—get update && \
    /usr/bin/apt—get install —y curl && \
    curl —SL https://deb.nodesource.com/setup_18.x I bash — && \
    /usr/bin/apt—get update && \
    /usr/bin/apt—get upgrade —y && \
    /usr/bin/apt—get install —y nodejs ffmpeg
WORKDIR /home/app

ENTRYPOINT [ "bash" ]